version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:14.2
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  go:
    container_name: go
    build:
      context: .
    env_file:
    - .env
    depends_on:
      postgres:
        condition: service_healthy # waiting until heathcheck of postgres is good
    ports:
      - "3000:3000"

volumes:
  dbdata: # persist database
